# Generated by Django 4.2 on 2023-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=50)),
                ('Your_Email', models.EmailField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField()),
                ('apt_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
